CREATE TABLE devices (
    id                  serial PRIMARY KEY,
    mac                 TEXT,
    via                 TEXT,
    ip                  TEXT,
    hostname            TEXT,
    device_name         TEXT,
    segment             TEXT,
    registered          boolean,
    access              TEXT,
    permit              TEXT,
    priority            INT,
    active              boolean,
    rxbytes             BIGINT,
    txbytes             BIGINT,
    uptime              BIGINT,
    first_seen          BIGINT,
    last_seen           BIGINT,
    link                TEXT,
    auto_negotiation    boolean,
    speed               INT,
    duplex              boolean,
    port                INT
);

CREATE TABLE devices_history (
    id                  serial PRIMARY KEY,
    mac                 TEXT,
    via                 TEXT,
    ip                  TEXT,
    hostname            TEXT,
    device_name         TEXT,
    segment             TEXT,
    registered          boolean,
    access              TEXT,
    permit              TEXT,
    priority            INT,
    active              boolean,
    rxbytes             BIGINT,
    txbytes             BIGINT,
    uptime              BIGINT,
    first_seen          BIGINT,
    last_seen           BIGINT,
    link                TEXT,
    auto_negotiation    boolean,
    speed               INT,
    duplex              boolean,
    port                INT
);